# Generated by Django 4.2.2 on 2023-07-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contents',
        ),
        migrations.AddField(
            model_name='course',
            name='contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.content'),
        ),
    ]
